version: '3.8'
services:
  backend:
    build:
      context: .
      target: backend-development
    working_dir: /app
    user: "1000"
    ports:
      - "5005:5005"
      - "8080:8080"
    environment:
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
    volumes:
      - ./backend/:/app
    depends_on:
      - mongo

  frontend:
    image: node:18-alpine
    working_dir: /app
    user: "1000"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
    command: sh -c "npm install && npm start"
    depends_on:
      - backend

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mixify_mongo_data:/data/db
      - mixify_mongo_config:/data/configdb

volumes:
  mixify_mongo_data:
  mixify_mongo_config:
