name: Deploy to fly.io

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  qa:
    uses: ./.github/workflows/qa.yml
    secrets:
      SONAR_TOKEN_BACKEND: ${{ secrets.SONAR_TOKEN_BACKEND }}
      SONAR_TOKEN_FRONTEND: ${{ secrets.SONAR_TOKEN_FRONTEND }}

  build:
    name: "Build & Deploy"
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install flyctl"
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: "Deploy to fly.io"
        run: flyctl deploy --remote-only