name: Deploy to fly.io

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  qa:
    uses: ./.github/workflows/qa.yml
    secrets:
      SONAR_TOKEN_BACKEND: ${{ secrets.SONAR_TOKEN_BACKEND }}
      SONAR_TOKEN_FRONTEND: ${{ secrets.SONAR_TOKEN_FRONTEND }}

  build:
    name: "Build & Deploy"
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install JDK"
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: "Install node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install flyctl"
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: "Build frontend"
        working-directory: frontend
        run: npm install && npm run build
      - name: "Copy assets"
        run: cp -r frontend/build backend/src/main/resources/static
      - name: "Build backend"
        working-directory: backend
        run: mvn -B package -D maven.test.skip --file pom.xml
      - name: "Deploy to fly.io"
        run: flyctl deploy --remote-only